ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS education VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS valid BOOLEAN NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date DATE NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at DATE NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at DATE NOT NULL;
